version: '3.7'

services:
  laravel-web:
    container_name: laravel-web
    build:
      dockerfile: Dockerfile.dev
      context: ./docker/nginx
    ports:
    - 8080:80
    volumes:
    - ./:/code
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  laravel-php:
    container_name: laravel-php
    build:
      dockerfile: Dockerfile.dev
      context: ./docker/php
    volumes:
    - ./:/code
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=laravel.local"

  laravel-mysql:
    container_name: laravel-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
    - 3306:3306

  laravel-test-mysql:
    container_name: laravel-test-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
    - 3307:3306

  laravel-adminer:
    container_name: laravel-adminer
    image: adminer
    restart: always
    ports:
    - 8090:8080

  laravel-redis:
    container_name: laravel-redis
    image: redis
    ports:
    - 6379:6379

  laravel-mail:
    container_name: laravel-mail
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025